---
- name: play for nodejs deployment
  hosts: localhost
  vars:
    container_name: node-app
    container_port: 3000
    host_port: 3000
    rollback_tag: rollback
  tasks:
    - name: Remove existing rollback image
      command: docker image rm {{container_name}}:rollback
      ignore_errors: yes
    - name: Stop and remove existing container if to avoid port conflict
      command: docker rm -f {{ container_name }}
      ignore_errors: yes
    - name: Tag current image for rollback for backup of image
      command: docker tag {{ container_name }}:latest {{ container_name }}:{{ rollback_tag }}
    - name: Building the docker container
      command: docker build -t  {{ container_name }}:latest /Users/maitri/node-app/
    - name: Deploy the latest Docker image
      command: docker run -d --name {{ container_name }} -p {{ host_port }}:{{ container_port }}  {{ container_name }}:latest
